### ISSUE TITLE
Actual content is stuck in a branch

### ISSUE THREAD

**Issue by ryscher** [metadatacenter-attic/cedar-cee-demo-generic#1]
This repository has the default branch set to `master`, which is essentially empty. The actual CEE code is in branch `develop`. It would be useful to merge `develop` into `master`, or change the default branch to `develop`.

**Comment by martinjoconnor** [comment]
It looks like this repo is not part of our CEDAR release process. So no code has been released to master yet (which we have just renamed to main to be in sync with other CEDAR repos).

Are you using this repo? If so, we will look at releasing it.

**Comment by ryscher** [comment]
This was the code that CEDAR developed in response to Dryad's work to integrate the CEE with our system. The code in the other repository is not functional for an "embeddable" system, because it can only be embedded into systems that use an Angular UI. We are currently using the code from this repository in our development/testing systems, and hope to eventually use it in production.

**Comment by martinjoconnor** [comment]
We are going to fix this. Hopefully, it will be ready in the next few days.

**Comment by ryscher** [comment]
This issue has been fixed with current versions of the CEE.
